# Generated by Django 5.2.3 on 2025-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='matches',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
