# Generated by Django 5.2.3 on 2026-01-19 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_matches_alter_player_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(max_length=32)),
                ('rank', models.CharField(default='Unranked', max_length=32)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.season')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'wins'], name='players_pla_season__f2a3d2_idx'), models.Index(fields=['season', 'matches'], name='players_pla_season__4a9a7b_idx')],
                'unique_together': {('season', 'discord_id')},
            },
        ),
    ]
