# Generated by Django 5.2.3 on 2026-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_season_playerseasonstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank_last_sync',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
