# Generated by Django 5.2.3 on 2026-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_rank_last_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstat',
            name='rank',
            field=models.CharField(default='Unranked', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
