# Generated by Django 5.2.3 on 2026-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_playerseasonstat_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstat',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
