# Generated by Django 5.2.3 on 2026-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_playerseasonstat_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
