[33m1b48b9a[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mdev-voice[m[33m, [m[1;31morigin/dev-voice[m[33m)[m ui: profile as dynamic image card with rank icons and controls
[33m2ece1d1[m ui: improve map veto image (overlay, badge, gradient, ban order)
[33m34b637f[m ui: polish draft image layout (icon slot, centered text, ellipsis, crisp resize)
[33m63a1b49[m upd: исправление команд бота
[33m64c2d23[m ui: improve lobby/leaderboard images (cards, centering, crisp rank icons)
[33mc3f2bfc[m fix: исправил генерацию картинки с задвоением(2)
[33mc6ef10e[m fix: исправил генерацию картинки с задвоением
[33m64974fe[m fix: исправил ошибки и добавил обнуление статистики
[33mc038f45[m fix: update player rank/username, include captains in stats, and show display names in images
[33m82385d9[m fix(matches): корректный set_winner без ничьей и с атомарными апдейтами - views: импорт F, валидация через SetWinnerSerializer, транзакция,   защита от дублей, журналирование события - api_client: set_winner через общий _request - settings: убран дубликат ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS
[33ma92849f[m fix(admin): убрать двойную регистрацию Match и навести порядок в settings - admin.py: объединён в один класс @admin.register(Match); удалён дубликат - добавлен inline событий и валидация дублей игрока в обеих командах - settings.py: оставлен один блок ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS, дубликаты удалены
[33m5b86cbd[m fix(matches): корректное начисление побед/матчей и запрет дублей - set_winner: устраняем игроков в обеих командах, апдейты через F(), идемпотентность
[33m7c05169[m Устранил ошибки ошибки, сделал немного чище код
[33m864a9f1[m fix(api): корректный возврат открытого ответа из _request + мелкая чистка leaderboard - _request больше не закрывает resp внутри: вызывающий код управляет контекстом - добавлен set_http_session(...) для явной инициализации глобальной сессии - get_leaderboard_top: читаем body один раз (косметика)
[33m79bd6bb[m fix(wins): надёжное подтверждение побед и защита от потери результата - api_client.save_match_result теперь возвращает (ok, data) и логирует тело ответа - Lobby.register_win: ставим флаг victory_registered только после успешного ответа API;   добавлен asyncio.Lock для защиты от двойного клика - Lobby.close_lobby: показываем кнопки победы только после появления match_id   (ожидание с таймаутом вместо фиксированного sleep) - Улучшены логи ошибок при сохранении и удалении канала
[33m074c8fe[m ui(draft): ник+ранг больше не перекрываются - generate_draft_image: фиксированные боксы столбцов, иконка ранга всегда справа,   ник слева с автоподбором размера под ширину; подсветка топ-3 сохранена ui(final): сделал прозрачнее фон и панели на финальной картинке - overlay: alpha 120 → 70 (карта просматривается сильнее) - панели атаки/защиты: alpha 160 → 110 + тонкий светлый контур - читаемость заголовков сохранена ui(leaderboard): подсветка ТОП-3 и авто-подбор размера ника - generate_leaderboard_image: места 1–3 рендерятся цветами GOLD/SILVER/BRONZE - ник подгоняется под ширину колонки (_fit_font), добавлена обводка - ранговая иконка выровнена по центру строки
[33m46cf94f[m feat(top3): подсветка глобального топ-3 в лобби и в итоговых командах + фикс шрифта лидераборда - image_generator: добавлены цвета золото/серебро/бронза и helper _color_for_top;   generate_lobby_image/ generate_draft_image красят имена по discord_id из глобального топа;   generate_leaderboard_image теперь использует get_font() с fallback’ами (без падений). - api_client: get_leaderboard_top(limit=3) — отдаёт список discord_id топ-игроков,   пробует /players/leaderboard/, затем /players/top10/. - lobby: во всех местах формирования players_data добавлен discord_id и   вместо локальной сортировки по wins тянем глобальный топ-3. - draft: в end_draft перед рендером подтягиваем топ-3 и передаём в генератор; players_data включает discord_id.
[33m191eb09[m ui(final): крупная картинка финала вместо маленького превью - image_generator.generate_final_match_image: 1280×720, cover-фон карты, тёмный слой, колонки «Атака/Защита», авто-подбор шрифтов - draft.send_map_embed: формируем списки игроков по сторонам и отправляем только файл-картинку (без embed)
[33macc3a71[m fix(maps): корректные пути к превью карт и единый поиск файлов - карты ищем в modules/maps (и fallback: modules/pictures/maps), поддерживаем webp/png/jpg/jpeg - generate_map_ban_image: удалён локальный MAP_ICONS_PATH, вместо него _find_map_image + прямое открытие/resize - generate_final_match_image: также использует _find_map_image для webp/png/jpg
[33mfcfab8b[m ui: все картинки без embed + корректный выбор сторон - lobby.close_lobby: состав лобби отправляется как файл, без embed - draft.end_draft: команды перед драфтом — только картинка (обновляем вложение) - map draft: одно «живое» сообщение с картинкой и кнопками; обновляем attachments - выбор сторон: теперь делает капитан другой команды (относительно последнего банившего) - финальный анонс карты/сторон — только файл, без embed
