# Generated by Django 5.2.3 on 2025-06-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('winner_team', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Team 1'), (2, 'Team 2')], null=True)),
                ('map_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Карта матча')),
                ('sides', models.JSONField(blank=True, null=True, verbose_name='Стороны команд (атака/защита)')),
                ('captain_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_captain1', to='players.player')),
                ('captain_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_captain2', to='players.player')),
                ('team_1', models.ManyToManyField(blank=True, related_name='matches_in_team1', to='players.player')),
                ('team_2', models.ManyToManyField(blank=True, related_name='matches_in_team2', to='players.player')),
            ],
        ),
    ]
