# Generated by Django 5.2.3 on 2025-09-09 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Матч создан'), ('win_set', 'Победитель установлен'), ('note', 'Событие')], max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['match', 'created_at'], name='matches_mat_match_i_c2d8c6_idx'), models.Index(fields=['type'], name='matches_mat_type_ec8b73_idx')],
            },
        ),
    ]
