# Generated by Django 5.2.3 on 2026-02-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchevent',
            name='matches_mat_match_i_c2d8c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchevent',
            name='matches_mat_type_ec8b73_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='lobby_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Название лобби'),
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('2x2', '2x2'), ('3x3', '3x3'), ('4x4', '4x4'), ('5x5', '5x5')], db_index=True, default='5x5', max_length=3, verbose_name='Режим лобби'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
