# Generated by Django 5.2.3 on 2026-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_matchevent_matches_mat_match_i_c2d8c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='External id (bot)'),
        ),
    ]
