# Generated by Django 5.2.3 on 2026-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='match',
            name='forfeit',
            field=models.BooleanField(default=False, verbose_name='Форфит'),
        ),
        migrations.AddField(
            model_name='match',
            name='forfeit_reason',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Причина форфита'),
        ),
        migrations.AddField(
            model_name='match',
            name='lobby_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Lobby ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='overtime',
            field=models.BooleanField(default=False, verbose_name='Овертайм'),
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Регион/сервер'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Счёт Team 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Счёт Team 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('abandoned', 'Abandoned'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16, verbose_name='Статус матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='External id (bot)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Team 1'), (2, 'Team 2')], null=True, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('win_set', 'Win Set'), ('status_changed', 'Status Changed')], max_length=64),
        ),
    ]
