# Generated by Django 5.2.3 on 2026-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_duration_seconds_match_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_ranked',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Учитывать матч в статистике'),
        ),
    ]
