# Generated by Django 5.2.3 on 2026-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_is_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='discord_channel_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Channel ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='discord_guild_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Guild ID'),
        ),
    ]
