# Generated by Django 5.2.3 on 2026-06-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_matchevent_type'),
        ('matches', '0007_match_discord_channel_id_match_discord_guild_id'),
    ]

    operations = [
    ]
