# Generated by Django 5.2.3 on 2026-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_merge_20260624_0924'),
        ('players', '0006_alter_playerseasonstat_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='External ID (bot)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sides',
            field=models.JSONField(blank=True, null=True, verbose_name='Стороны команд'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'created_at'], name='matches_mat_status_98f455_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mode', 'is_ranked'], name='matches_mat_mode_05ede1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['discord_guild_id', 'discord_channel_id'], name='matches_mat_discord_173de0_idx'),
        ),
    ]
